### PR TITLE
Add Gin <-> Arpc integration example leveraging webchat

### LINKED ISSUE #62: Gin -> ARPC integration
I put together a gist of the bones of my integration or ARPC with Gin. Not sure if something like this is already out there. I wanted to share in case it wasn't. It took a big of figuring out how to properly register the web socket listener with Gin and a http handler and how to get that listener to the arpc `Serve` invocation.

https://gist.github.com/KevM/4aafd4873df884cc95fc8e606ab0f4e4

### PR DESCRIPTION
**Pull request by KevM**
Closes #62 

I took a swing at modifying the existing chat example to be hosted by Gin and add a simple web API exposing the room user identifiers via `GET /room`

Let me know what you think. I wasn't sure you wanted a dependency on Gin, so I made the example folder it's own go module. If you know a better way, I am happy to oblige.

### CODE REVIEW

**Comment by lesismal** [comment]
arpc core implementation imports std only,the arpc/go.mod only declares the package name but doesn't run go mod tidy to keep the core clean and zero dependencies.
So, please don't generate go.mod and go.sum.

Please don't use too many 3rd libs if not needed, don't commit bin files:
image

**Comment by lesismal** [comment]
I'll close this pr cause the bin file has been in this branch's commit history, reset or re-fork a clean branch will be better.

**Comment by KevM** [comment]
I'm not sure what to do. The example requires Gin. I'll let you do what you want with this.

**Comment by lesismal** [comment]
ok, I'll do it, tks bro!

**Pull request closed without merging**
